using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine.UIElements;

namespace samirin33.SamirinBoothManager.UI.Parts
{
    /// <summary>
    /// UI/Parts フォルダ内の UXML を UIToolkit カスタム要素として登録する。
    /// 親 UXML では xmlns:sbm="samirin33.SamirinBoothManager.UI.Parts" を宣言し、
    /// &lt;sbm:SBM_Base /&gt; のように要素名（ファイル名）で利用できる。
    /// </summary>
    [InitializeOnLoad]
    public static class SBM_UIParts
    {
        public const string PartsAssetFolder = "Assets/samirin33/SamirinBoothManager/UI/Parts";
        public const string UxmlNamespace = "samirin33.SamirinBoothManager.UI.Parts";
        const string GeneratedFilePath = "Assets/samirin33/SamirinBoothManager/Script/Editor/SBM_UIParts.Generated.cs";

        static SBM_UIParts()
        {
            SyncGeneratedElements();
        }

        public static void SyncGeneratedElements()
        {
            var partNames = CollectPartNames();
            var source = BuildGeneratedSource(partNames);

            var directory = Path.GetDirectoryName(GeneratedFilePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            if (File.Exists(GeneratedFilePath) && File.ReadAllText(GeneratedFilePath) == source)
                return;

            File.WriteAllText(GeneratedFilePath, source, Encoding.UTF8);
            AssetDatabase.Refresh();
        }

        static List<string> CollectPartNames()
        {
            var partNames = new List<string>();
            var guids = AssetDatabase.FindAssets("t:VisualTreeAsset", new[] { PartsAssetFolder });
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (!path.EndsWith(".uxml", StringComparison.OrdinalIgnoreCase))
                    continue;

                partNames.Add(Path.GetFileNameWithoutExtension(path));
            }

            partNames.Sort(StringComparer.Ordinal);
            return partNames;
        }

        /// <summary>
        /// Script/Editor/{PartName}.cs がある場合は手書き実装として生成対象外にする。
        /// </summary>
        static bool HasHandWrittenPart(string partName)
        {
            var path = $"Assets/samirin33/SamirinBoothManager/Script/Editor/{partName}.cs";
            return File.Exists(path);
        }

        static string BuildGeneratedSource(IReadOnlyList<string> partNames)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using UnityEngine.UIElements;");
            builder.AppendLine();
            builder.AppendLine("namespace samirin33.SamirinBoothManager.UI.Parts");
            builder.AppendLine("{");

            foreach (var partName in partNames)
            {
                if (HasHandWrittenPart(partName))
                    continue;

                builder.AppendLine($"    public class {partName} : SBM_UxmlPartElement");
                builder.AppendLine("    {");
                builder.AppendLine($"        public new class UxmlFactory : UxmlFactory<{partName}, UxmlTraits> {{ }}");
                builder.AppendLine("        public new class UxmlTraits : VisualElement.UxmlTraits { }");
                builder.AppendLine($"        public {partName}() : base(nameof({partName})) {{ }}");
                builder.AppendLine("    }");
                builder.AppendLine();
            }

            builder.AppendLine("}");
            return builder.ToString();
        }
    }

    public abstract class SBM_UxmlPartElement : VisualElement
    {
        protected SBM_UxmlPartElement(string partName)
        {
            var path = $"{SBM_UIParts.PartsAssetFolder}/{partName}.uxml";
            var template = AssetDatabase.LoadAssetAtPath<VisualTreeAsset>(path);
            template?.CloneTree(this);
        }
    }

    class SBM_UIPartsAssetPostprocessor : AssetPostprocessor
    {
        static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (!ContainsPartsAsset(importedAssets)
                && !ContainsPartsAsset(deletedAssets)
                && !ContainsPartsAsset(movedAssets)
                && !ContainsPartsAsset(movedFromAssetPaths))
                return;

            SBM_UIParts.SyncGeneratedElements();
        }

        static bool ContainsPartsAsset(string[] paths)
        {
            if (paths == null)
                return false;

            foreach (var path in paths)
            {
                if (path.StartsWith(SBM_UIParts.PartsAssetFolder, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }
    }
}
